version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Docsify.dockerfile
    ports:
      - 3000:3000
      - 35729:35729
    tty: true
    volumes:
      - ./docs:/usr/local/docsify/
